### ISSUE TITLE
View.removeNodes() not working for containerless components/compose

### ISSUE THREAD

**Issue by EugeneIvakhiv** [aurelia/templating#543]
**I'm submitting a bug report**

* **Library Version:**
1.4.1

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Browser:**
Chrome XX

* **Language:**
all

**Current behavior:**
View returned by TemplatingEngine.enhance() when containerless does not remove DOM nodes via removeNodes() method

**Expected/desired behavior:**

Same as with "container" scenario, the View should cleanup its nodes.
Here's the demo: https://plnkr.co/edit/Ripbqy2QvTdd8CAK7CjR?p=preview
In the demo the blue component is properly cleaned up, the red one (containerless) is not.

* **What is the motivation / use case for changing the behavior?**
When operating with views programmatically it's necessary for cleanup (add/remove views).

**Comment by EisenbergEffect** [comment]
Try updating your templating library to the latest release. This should be fixed.

**Comment by EugeneIvakhiv** [comment]
Hi Rob,

Thanks for looking into this.
Actually this was tested locally on most recent sources with your [commit](https://github.com/aurelia/templating/commit/5793d9c11bbb1c33c39afc7bcb1e7506de6bed90) and behavior is not any different from the version used in the plunkr. So, this issue is not fixed and should be reopened.

BTW, that commit broke `.fragment` API. I've left [comment](https://github.com/aurelia/templating/commit/5793d9c11bbb1c33c39afc7bcb1e7506de6bed90#commitcomment-21676873) with the details
